services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=comotDatabase'
      - 'POSTGRES_PASSWORD=secreEmmanuelPassword'
      - 'POSTGRES_USER=root'
    ports:
      - '5432'
